<?php
// Copy to config/config.php in the instance dir and fill in. Never commit a real config.
return [
    // The one Pixelfed instance meenow talks to. Hard-whitelisted by the proxy.
    'home_instance' => 'pixelfed.social',

    'db' => [
        'host' => 'localhost',
        'name' => '', // your MySQL database
        'user' => '',
        'pass' => '',
    ],

    'vapid' => [
        'subject' => 'mailto:admin@example.com', // contact for push services
        // Keypair JSON generated by scripts/gen-vapid.php, lives in config/
        // (outside the docroot): {"publicKey": "...", "privateKey": "..."}
        'key_file' => __DIR__ . '/vapid.json',
    ],

    // Secret in the cron URL: https://meenow.de/cron?action=tick&key=...
    // Generate: php -r 'echo bin2hex(random_bytes(32)), PHP_EOL;'
    'cron_key' => '',

    // xkcd mirror cache (GET /xkcd.json refreshes it on first request per TTL).
    // Any writable off-docroot path; the default is server/cache/ in the app dir.
    // 'xkcd_cache' => __DIR__ . '/../cache/xkcd.json',
    // 'xkcd_ttl_s' => 21600,

    // Per-IP rate limit for the OPEN proxy endpoints (app registration, token
    // exchange) and /xkcd.json — everything else needs a Bearer token first.
    // Max requests within window_s.
    'rate_limit' => [
        'window_s' => 60,
        'max' => 300,
    ],
];
